export const defaultBranding = {
  firmName: "TaxWise Partners",
  tagline: "Precision filings. Personalised insights.",
  primaryColor: "#0ea5e9",
  accentColor: "#14b8a6",
  logoUrl: "",
  faviconUrl: "",
  emailSignature: "Warm regards,\nTaxWise Partners",
  invoiceNote: "This document is generated by TaxWise. For assistance mail care@taxwise.in",
}

export const BRANDING_STORAGE_KEY = "acternity.dashboard.branding"
